<section class="page">
    <div class="container">
        <div class="content">
            <h1>Terms and Conditions CoinSniper</h1>
            <h2>Last update: January 2022</h2>

            <h2>1	Introduction</h2>
            <p>1.1	CoinSniper is a cryptocurrency voting platform on which new cryptocurrency projects can be listed and viewed.</p>
            <p>1.2	CoinSniper provides the following Services:</p>
            <p>1.2.1	CoinSniper offers a Platform where any (legal or natural) person can submit a cryptocurrency project by using the submission form on the website: https://coinsniper.net (the Website). A person who submits a coin will be hereinafter referred to as a Lister. Submitted Coins instantly become visible on the New Listings Page. Coins will initially be placed in the category “New” on the Website.</p>
            <p>1.2.2	CoinSniper offers the possibility for natural persons to become a Voter. A Voter may vote on a Submitted Coin. To become a Voter, it is mandatory to create an Account (as defined below) on the Website.</p>
            <p>1.2.3	Voters can upvote Submitted Coins once these are listed. Submitted Coins with more than 500 votes will appear in the categories “All Time” and “Today” on the Website.</p>
            <p>1.2.4	CoinSniper offers advertising services through, among other things, banners on the Website and promoted spots for Submitted Coins.</p>
            <p>Listers and Voters will hereinafter also be referred to as a User or Users.</p>
            <p>1.3	CoinSniper does not verify any Submitted Coins, Listers or Voters. Coin listings on the Website are for informational purposes only. CoinSniper does not provide any financial advice, act as financial services provider or broker, or in any other way aid in the formation of any transactions in cryptocurrency or otherwise.</p>
            <p>1.4	The market for the digital assets, including but not limited to cryptocurrency as listed on the Website, is still new and uncertain. Unlike most currencies or assets, which are backed by governments or other legal entities, or by other commodities such as gold or silver, digital assets are a unique type of asset, backed by technology and trust. Digital assets are an as-yet autonomous and largely unregulated global system of digital asset service providers and individuals. Investors put their trust in a digital, decentralised and partially anonymous system that relies on peer-to-peer networking and cryptography to maintain its integrity. Consequently, market prices for digital assets can be highly volatile and unpredictable. Whether the future market price for a digital asset will move up or down is a speculation and unknowable and digital assets may even become worthless. There is no central bank or other third party that can take corrective measures to protect the value of a digital asset. The User is aware of this market risk and should be cautious about digital assets. Moreover, the cryptocurrency listed on the Website could potentially be Scams, i.e. designed to either by object or effect induce market participants to invest financial resources that will not be recoverable once investments are made. Each User is responsible to Do Your Own Research (DYOR) regarding any information, specifically regarding cryptocurrency, listed on the Website.</p>
            <p>1.5	These terms and conditions (Terms), along with the Privacy Policy (insert link privacy policy), constitute a legally binding agreement made between the User (whether personally or on behalf of a legal person, partnership or otherwise) and CoinSniper and its affiliated companies, websites (including the Website), applications and tools, concerning the access to and the use of the Website and Platform as well as any other media form, media channel, mobile website or mobile application related or connected thereto.</p>
            <p>1.6	The use of any the Services provided by CoinSniper is conditioned upon User’s and acceptance of and compliance with these Terms.</p>

            <h2>2	Eligibility</h2>
            <p>2.1	To access or use the Services, the User must be at least 18 years old. A User may not use the Services if the CoinSniper has terminated any of User’s accounts or banned the User.</p>

            <h2>3	Content on the platform</h2>
            <p>3.1	Content added, created, uploaded, submitted, distributed, posted, or otherwise obtained through the Platform and/or Website by Users, including content that is added to the Platform and/or Website in connection with Users linking their accounts to third party websites and services, is collectively referred to as User Generated Content.</p>
            <p>3.2	The Platform and/or Website offered by CoinSniper contains content which consists of both User Generated Content and content uploaded by CoinSniper (CoinSniper Content, collectively with User Generated Contend referred to as the Content).</p>

            <h2>4	User Representations</h2>
            <p>4.1	The User may not access or use the Platform, Website and/or Services of CoinSniper for any other purpose other than for which CoinSniper makes it available. The Platform, Website and/or Services may not be used in connection with any commercial endeavours, except those that are endorsed and approved by CoinSniper. When the User uses the Services of CoinSniper, the User hereby represents and warrants to refrain from:</p>
            <p>4.1.1	Using the Platform, Website and/or Services in any wat that this is or may be damaging to the Website, Platform, or CoinSniper;</p>
            <p>4.1.2	Using the Platform, Website and/or Services in a way that impacts Users’ access to the Website;</p>
            <p>4.1.3	Uploading any information to the Platform and/or Website that is false or incorrect;</p>
            <p>4.1.4	Using the Platform, Website and/or Services contrary to applicable laws and regulations;</p>
            <p>4.1.5	Attempting to impersonate another User or person or using the username of another User; and</p>
            <p>4.1.6	Engaging in any automated use of the Website, such as using data mining, robots, automated voting, or similar data gathering and extraction tools.</p>
            <p>4.2	When the User creates or makes available User Generated Content, the User hereby represents and warrants that:</p>
            <p>4.2.1	The User Generated Content does not in any way induce persons to enter into transactions that by object, effect or otherwise lead to (practically) irretrievable loss of invested money or digital assets such as cryptocurrency other than as a result of market fluctuations;</p>
            <p>4.2.2	The User is the creator and owner of the User Generated Content of or has the necessary licences, rights, consents, or releases to make such User Generated Content available on the Website;</p>
            <p>4.2.3	The User Generated Content does not infringe any intellectual property rights, including without limitation copyrights, patents or trademark rights of any third party;</p>
            <p>4.2.4	The Content is not obscene, lewd, lascivious, filthy, violent, harassing, fraudulent libellous or slanderous or otherwise objectionable (as determined by CoinSniper), and does not ridicule, mock disparage, intimidate, or abuse anyone; and</p>
            <p>4.2.5	The Content does not otherwise violate, or link to material that violates any provision of these Terms or any applicable law or regulation.</p>

            <h2>5	Access and Interference</h2>
            <p>5.1	CoinSniper does not actively monitor, screen and/or edit the User Generated Content on the Platform and/or Website.</p>
            <p>5.2	If any User finds that any Content on the Platform or Website infringes applicable legal and regulatory provisions, in particular in case of clearly illegal content (e.g. defaming, denigrating or infringing upon intellectual property rights), the User shall notify CoinSniper by sending a Notice-and-Take-Down request (NTD request) [insert link to NTD policy] to info@coinsniper.net. In such case, the User must provide CoinSniper with all information necessary to enable CoinSniper to identify the Content in question and take further actions if necessary, such as:</p>
            <p>‐	Description of the (User Generated) Content in dispute and the precise location;</p>
            <p>‐	The reasons why the (User Generated) Content should be removed, preferably including the legal and factual basis; and/or</p>
            <p>‐	Name and other available information of the User who uploaded the User Generated Content.</p>
            <p>5.3	CoinSniper has the right to remove and/or block certain User Generated Content without reason and without prior notice after receipt of a NTD request or similar notice. In the event a User uploads User Generated Content that infringes Clause 4.2.1, CoinSniper may post (parts of) the relevant User Generated Content on www.scamsniper.net, in which regard User waives any claims against CoinSniper in advance.</p>

            <h2>6	Third Party Websites and Content</h2>
            <p>The Website may contain Content that links to other websites, services or resources on the internet, and other websites, services or resources may contain links to the Website. The User accesses third party websites at their own risk. These other websites are not under CoinSniper’s control, and the User acknowledges that CoinSniper is not responsible or liable for the content, functions, accuracy, legality, appropriateness, or any other aspect of such websites or resources. The inclusion of any such link does not imply endorsement by CoinSniper of or any association with third-party operators. The User further acknowledges and agrees that CoinSniper will not be responsible or liable for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any such content, goods, or services available on or through any such third-party website or resource.</p>

            <h2>7	Advertisements and Paid Promotions</h2>
            <p>7.1	CoinSniper offers banner advertisement spots and promoted coin spots (collectively referred to as Paid Content). CoinSniper is not responsible for the Paid Content that is submitted on the Website.</p>
            <p>7.2	Any listing of cryptocurrency can be listed in the top promoted coin section, subject to payment of a fee. For the avoidance of doubt, the listings shown in the top promoted list are not verified by CoinSniper. CoinSniper may delete these listings from this section and/or the Website at any time and without prior notice after receipt of a NTD request or similar notice (also see clause 5).</p>

            <h2>8	Account</h2>
            <p>8.1	In order to vote on Submitted Coins via the Platform and/or Website, CoinSniper requires the prospective Voter to register and create an account with CoinSniper (the Account). To create an Account, the prospective Voter must, among other things, provide an e-mail address and choose a strong password. The e-mail address and chosen password, together, form the Login Credentials.</p>
            <p>8.2	The prospective Voter is fully responsible for non-disclosure of its Login Credentials and the use of its Account to unauthorised persons or entities. The prospective Voter may not allow use of its Account by any third party nor others that do not have the authority to represent prospective Voter. The prospective Voter guarantees that any third party that uses its Account is authorized to represent the prospective Voter. If the prospective Voter suspects that its Account’s security has been breached, the prospective Voter shall report this immediately to info@coinsniper.net.</p>
            <p>8.3	The prospective Voter shall only provide correct and complete information when creating an Account on the Platform. The prospective Voter is responsible for the accuracy of the data in its Account.</p>
            <p>8.4	The Voter may request to cancel/terminate its Account by contacting CoinSniper. CoinSniper may need to retain certain information as required by law or as necessary for its business purposes. For more information about the processing of personal data, please see the Privacy Policy [@insert  link Privacy Policy].</p>
            <p>8.5	After receipt of a NTD request or similar notice, CoinSniper may always, at its own discretion, suspend, block, or delete the Account of the Voter. The Voter is not entitled to any compensation by CoinSniper in connection with the suspension, blocking or deletion of the Account by CoinSniper and the Voter hereby waives any right to any compensation of damages.</p>

            <h2>9	Disclaimers</h2>
            <p>9.1	The Content on the Website and/or Platform is strictly for informational purposes. Nothing on the Website and/or Platform will constitute or be construed as an offering of any currency, coin, crypto, NFT or other financial instrument or as investment advice or investment recommendations (such as recommendations as to whether purchase a currency or instrument) or a recommendation as to an investment strategy by CoinSniper.</p>
            <p>9.2	CoinSniper does not verify any User Generated Content, including but not limited to cryptocurrency/coin listings, and therefore Submitted Coins listed on the Website could potentially be designed to either by object or effect induce persons to invest moneys, cryptocurrency or other valuables that will be irretrievably lost or in any other way defraud persons (i.e., Scams). It is the Users sole responsibility to do its own research regarding Submitted Coins. CoinSniper excludes liability for any damages suffered as a result of these Scams. Only after receipt of an NTD request or similar notice, CoinSniper may decide to block or remove Submitted Coins or other User Generated Content.</p>
            <p>9.3	The Content on the Website and/or Platform is not a sufficient basis for an investment strategy and the User shall not use the Content as such. No Content on the Platform and/or Website is tailored to the specific needs of an individual, entity or group of individuals.</p>
            <p>9.4	CoinSniper expresses no opinion as to the future or expected value of any Submitted Coin, currency, security or other interest. CoinSniper does not in any way recommend or suggest an investment strategy of any kind.</p>
            <p>9.5	The User acknowledges that the User Generated Content provided on the Website and/or the Platform is submitted to CoinSniper by unrelated third-party providers. CoinSniper does not review the User Generated Content for accuracy, completeness or reliability and does not warrant or guarantee the accuracy, completeness, reliability, or any other aspect of User Generated Content. Only after receipt of an NTD request or similar notice, CoinSniper may decide to block or remove User Generated Content.</p>
            <p>9.6	The Content published on the Platform and/or Website may include inaccuracies or errors. CoinSniper does not guarantee the accuracy, completeness, timeliness, security, availability or integrity of the Services or any Content, and disclaims all liability for any errors or other inaccuracies relating to the Services and/or the Content. CoinSniper makes no representations about the suitability of the Services and/or any Content.</p>
            <p>9.7	The Service and Content are provided “as is” without warranty of any kind. CoinSniper disclaims all warranties and conditions that the Website and/or Platform or any email sent from CoinSniper are free of harmful components or Scams. CoinSniper hereby disclaims all warranties and conditions with regard to the Website, Platform, Service and Content, including all implied warranties and conditions.</p>

            <h2>10	Limitation of Liability</h2>
            <p>10.1	The User agrees to the following limitation of liability with respect to the use of the Platform, Website and Services:</p>
            <p>10.1.1	CoinSniper excludes liability for any damages suffered as a result of the use of the Platform, Website or the Content provided thereon, to the fullest extent permitted by applicable law.</p>
            <p>10.1.2	CoinSniper has no influence on the data and information that is transmitted between Users or the User Generated Content on the Platform and/or Website. Therefore, CoinSniper is not liable for this data and information. CoinSniper is also not liable for any data or information that is incomplete or inaccurate as a result of such transmission or that is transmitted wrongly.</p>
            <p>10.1.3	The User understands that all information posted on the Platform and/or Website is the sole responsibility of the person from which such information is originated. The User understands that Submitted Coins potentially could be Scams. Voting on and purchasing such coins will be the sole responsibility of the User. The User acknowledges that all the Content accessed by it using the Platform and/or Website is at its own risk and that the User will be solely responsible and liable for any damage or loss to itself or any other party resulting therefrom. CoinSniper will not be liable for any errors or omissions in such information or the Content. CoinSniper cannot guarantee the identity of any other Listers nor Voters with whom the User may interact in the course of using the Platform and/or Website</p>
            <p>10.1.4	If, for whatever reason, CoinSniper is liable for any damage of the User, its liability will be limited to an amount of EUR 100 or to the amount the insurance company of CoinSniper disburse in that specific case, whichever is lower.</p>
            <p>10.2	The User is at all times obliged to perform those acts reasonably required to limit or prevent (possible) loss and damage to one of the other Parties to this Agreement, regardless of whether this Party will be liable for such (possible) loss or damage.</p>
            <p>10.3	A claim will in any case lapse if CoinSniper is not notified in writing of the claim within one (1) year of the discovery of an event or circumstance that gives rise to or could give rise to liability.</p>
            <p>10.4	Nothing in these Terms will exclude or limit the liability of CoinSniper if this cannot be excluded or limited under the applicable law, such as in the case of intent or gross fault by CoinSniper.</p>

            <h2>11	Indemnification</h2>
            <p>11.1	Users, in particular Listers, shall indemnify, defend and hold harmless CoinSniper from any third-party claims, liability, damages and/or costs (including, but not limited to, attorney fees) arising from the use of the Services, Platform and/or Website, violation of the Terms or the infringement or violation by Users of any intellectual property or other right of any person or entity.</p>
            <p>11.2	CoinSniper reserves the right to assume the exclusive defence and control of any matter otherwise subject to indemnification by the User, in which event the User will assist and cooperate with CoinSniper asserting any available defences.</p>

            <h2>12	Intellectual Property</h2>
            <p>12.1	CoinSniper is the exclusive owner of all intellectual property rights vesting in and relating to the Services and the Platform, Website, CoinSniper Content if created by CoinSniper), documents and materials related thereto, such as – but not limited to – patents, patent applications, trademarks, trademark applications, database rights, service marks, trade names, copyrights, trade secrets, licenses, domain names, know-how, property rights and processes (Intellectual Property Rights).</p>
            <p>12.2	CoinSniper grants the User a non-transferrable, non-sublicensable, non-exclusive and revocable license intended for fair use of the CoinSniper Content, Services, the Website and the Platform.</p>
            <p>12.3	The User will not reproduce, resell, or distribute the above license, unless CoinSniper explicitly has given prior written consent to do so.</p>
            <p>12.4	The User guarantees to be the exclusive owner of all Intellectual Property Rights to the information that the User shares with CoinSniper or on the Platform and/or Website. CoinSniper will be granted a non-exclusive license by the User to use any materials provided by the User to CoinSniper. CoinSniper may also use this information in communications and advertisements in all media for the range offered by CoinSniper. The User guarantees to be authorised to grant this license to CoinSniper, without infringing applicable legislation and regulations or the rights of third parties.</p>

            <h2>13	Privacy</h2>
            <p>Please read our Privacy Policy <a href="/privacy-policy">coinsniper.net/privacy-policy</a>.</p>

            <h2>14	Miscellaneous</h2>
            <p>14.1	No omission or delay on the part CoinSniper in exercising any right, power or remedy under these Terms, shall prejudice or impair such right, power or remedy or be construed as a waiver thereof. Any single or partial exercise of such right, power or remedy shall not preclude any other or future exercise thereof or the exercise of any other right, power or remedy.</p>
            <p>14.2	CoinSniper reserves the right to unilaterally modify or replace these Terms at any time if CoinSniper finds this reasonably necessary and useful.</p>
            <p>14.3	If any provision of these Terms is found to be unenforceable or invalid, that provision will be limited or eliminated to the maximum extent necessary so that the rest of these Terms will remain in full force and effect and stay enforceable. Any such unenforceable or invalid provision shall be replaced or be deemed to be replaced by a provision that is considered to be valid and enforceable, and which interpretation shall be as close as possible to the intent of the invalid provision.</p>
            <p>14.4	Except as explicitly stated otherwise, any notices given to CoinSniper shall be given by email to the address listed in the contact information below. Any notices given to the User shall be given to the email address provided during the registration process, or such other address as each party may specify. Notice shall be deemed to be given twenty-four (24) hours after the email is sent, unless the sending party is notified that the email address is invalid. CoinSniper may also choose to send notices by regular mail.</p>
            <p>14.5	All provisions of these Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability.</p>

            <h2>15	Applicable Law and Competent Court</h2>
            <p>15.1	These Terms and any disputes in relation to these Terms shall be governed by and construed in accordance with the laws of the Netherlands.</p>
            <p>15.2	Unless mandatory law compels differently, all disputes resulting from or arising in connection with these Terms shall be exclusively submitted to the competent court of Midden-Nederland, the Netherlands, unless the dispute can be settled in an amicable fashion.</p>
            <p>15.3	Users domiciled within the European Union will benefit from any mandatory provision of the law of the country in which they are resident in.</p>

            <h2>16	Queries, Remarks and Suggestions</h2>
            <p>CoinSniper wants to offer its Users optimum Services. For any queries, remarks, or suggestions, please contact CoinSniper by sending an email to info@coinsniper.net.</p>

        </div>
    </div>
</section>
